version: "3"
services:
  auth:
    build: ./auth-api
  users:
    build: ./users-api
    environment: 
      AUTH_ADDRESS: auth
     # In Docker Compose, we need to manually define AUTH_SERVICE_SERVICE_HOST.
     # Unlike Kubernetes, this variable won't be automatically set to the service's IP.
     # Instead, we assign it the DNS name of the container (auth), since Docker Compose
     # uses service names for internal DNS (here it's the domain name system) resolution.
      AUTH_SERVICE_SERVICE_HOST: auth
    ports: 
      - "8080:8080"
  tasks:
    build: ./tasks-api
    ports: 
      - "8000:8000"
    environment:
      TASKS_FOLDER: tasks
    volumes:
      - /app/tasks