version: '3.8'

services:
  # The nginx container
  server:
    # We specify nginx image and we use stable-alpine tag version from docker hub, which based on very slim linux 
    # operating system layer
    image: 'nginx:stable-alpine'
    ports:
      # 80 - The port that the web server exposes to us from the internal container - from documentation:
      #  https://hub.docker.com/_/nginx 
      # 8000 - The port that will be exposes on our local machine
      - '8000:80'
    volumes:
      # We bind (mount) the nginx.conf file from our local machine to nginx.conf in the container.
      # etc/nginx/nginx.conf - We know that it will be in this path specifically from documentation
      # ro - Read Only, since the container should never change the configuration there 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # php:
  # mysql: 
  # compose:
  # artisan:
  # npm: