apiVersion: apps/v1  
kind: Deployment 
metadata: 
  name: users-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:  
      app: users
  template: 
    metadata: 
      labels:
        app: users 
    spec:
      containers: 
        - name: users 
          image: urielpa/kub-demo-users:latest
          # We can create file fo environment variables of to that on the fly like here.

          # localhost - For pod internal communication, so when 2 containers run in the same pod, Kubernetes allows us to send
          # request to the localhost address and then using the port which is exposed by the other container (the users).
          # So localhost is the magic address we can use inside of a pod. So if we have one container running in a pod, 
          # which executes some code which also runs on the server side so to say, inside of the pod and that code needs an
          # address we can use localhost as an adress if wanna send a request to another container running in the same pod.
          env: 
            - name: AUTH_ADDRESS 
              # value: localhost
              # So for the Signup in users-app.js we use the manually approach to show also that we can use the IP of the
              # service of the auth-service object by pulling its IP from kubectl get svc. 
              # So we show both way - the manually aproach like here, and the auto-generated environment variable by kubernetes
              # (check on users-app.js in the login for more details)
              value: "10.111.132.114"
        # - name: auth
        #   image: urielpa/kub-demo-auth:latest
