apiVersion: apps/v1  
kind: Deployment 
metadata: 
  name: users-deployment
spec: 
  replicas: 1
  selector: 
    matchLabels:  
      app: users
  template: 
    metadata: 
      labels:
        app: users 
    spec:
      containers: 
        - name: users 
          image: urielpa/kub-demo-users:latest
        - name: auth
          image: urielpa/kub-demo-auth:latest
